### ISSUE TITLE
Look for new trades to add-on to unshipped existing trades

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#11]
Compare the Send Cards list with the Sending list to determine if a new card can be accepted. This makes sense regardless of the value of the new card I think.

**Comment by Droogans** [comment]
I don't understand this feature. Can you explain it from beginning to end, with examples/data?

**Comment by tomreece** [comment]
@Droogans 

Given Pucauto has already committed to send some cards to user Foo according to bundling logic,
And those cards have not been marked as shipped by Me yet,
When Pucauto later sees that user Foo wants more cards that I have,
Then Pucauto might as well commit to send those cards too, regardless of their value.

Why weren't they part of the original bundle? Because perhaps the world state changed. Maybe user Foo now has more points in their PucaTrade account. Maybe I added more cards to my Haves list. Maybe user Foo added more cards to their Wants list.

Does that make sense?

**Comment by tomreece** [comment]
Implemented in #35
