### ISSUE TITLE
Windows users experiencing a crash when getting card_href in build_trades_dict()

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#37]
Not sure what's going on here. Investigate.

Reported by 2 users so far: Dominick and Tyler

Todo: Follow up with them when I'm able to reproduce and have a fix.

**Comment by tomreece** [comment]
I cannot reproduce this. I tried on a Windows Server 2012 virtual machine.

```
C:\Users\pucauto\Desktop\pucauto-0.4.0>python --version
Python 2.7.10

C:\Users\pucauto\Desktop\pucauto-0.4.0>python -m pip install -r requirements.txt

You are using pip version 7.0.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.4.1
in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): selenium==2.48.0 in c:
\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in c:\pyth
on27\lib\site-packages (from -r requirements.txt (line 3))
```

**Comment by tomreece** [comment]
Please comment here if you're experiencing this issue. Let me know what version of Windows, Python, Firefox, any details you know. Thanks.

**Comment by isutrumpet** [comment]
EDIT:  It appears to be working now upon downloading the latest .4 code.

I have had the same issue across 2 different systems (1 physical, 1 virtual) running the same versions of the software:

Windows 7
Python 3.5
Firefox 42

**Comment by tomreece** [comment]
@isutrumpet So it's working now for you?

When I tried to reproduce it I was on Windows Server 2012 R2, which I think is like Windows 8, Python 2.7.10, and Firefox 42.

**Comment by isutrumpet** [comment]
It's generally working, though I have been getting some odd buffer errors after sustained runs.  If they persist, I will provide the details.  Do you recommend Python 2.7.10 for this code?

**Comment by tomreece** [comment]
I use and primarily test against Python 2 so you'd probably have much better luck. I try to be Python 3 compatible but since I don't usually test specifically against it, I find bugs after the fact unfortunately. After long running, eventually Firefox and Selenium eat up more and more memory. Selenium is not the most efficient tool in the world, but it's our only option to bot against PucaTrade since they don't have an API.

**Comment by isutrumpet** [comment]
This might be worth a new issue thread itself, but here is a consistent error I get in a VM I am running:

File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 10055] An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full"

Windows 7 (4GB RAM allocated, if that matters)
python-2.7.10
Firefox 42

**Comment by tomreece** [comment]
@isutrumpet yeah that's deep in a library, can you make a new issue for this?

**Comment by tomreece** [comment]
@isutrumpet Are you still getting the original issue mentioned here in v0.4.1 of Pucauto? Check at your convenience and let me know.

**Comment by tomreece** [comment]
Can any Windows users confirm/deny this is happening to them please? Otherwise I'm going to close it in a week or two.

**Comment by tomreece** [comment]
Cannot reproduce and a few Windows users I contact frequently have reported no issues here. Closing this.
