### ISSUE TITLE
Incorrect Card Bundle

### ISSUE THREAD

**Issue by ChiefD425** [tomreece/pucauto#39]
I had an issue today where the same username caused an incorrect bundle to be generated.

<img width="766" alt="screen shot 2015-12-02 at 12 58 12 pm" src="https://cloud.githubusercontent.com/assets/15125708/11540827/8fe79ef2-98f4-11e5-8288-aec13700d04f.png">

<img width="332" alt="screen shot 2015-12-02 at 12 53 49 pm" src="https://cloud.githubusercontent.com/assets/15125708/11540684/dd2adfd6-98f3-11e5-8005-6c8a18444cb7.png">

**Comment by tomreece** [comment]
Oh! That's a good find. I'll fix that. Each user has a unique ID which I should have been using instead of their display name. My mistake, will fix and close this issue when fixed so you'll know. :)

**Comment by tomreece** [comment]
@ChiefD425 Fixed this in master. Haven't drafted a new release for it yet, will hold off on that. But if you want the fixed version now just download https://github.com/tomreece/pucauto/archive/master.zip or `git pull` if you're doing it the git way.
