### ISSUE TITLE
Add ability to blacklist users

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#44]
Suggested by Dominick.

> I have a suggestion for a feature if possible, but the idea I had was for a filter for usernames. The reason being is because for user who have names such as nm only or pack fresh. I've found are super stingy even with cards I myself have opened and just sleeved. If it's not possible it's no big deal just a small thing I thought of because I had someone send me back a few trades which I would argue are nm but maybe it's just me haha. Thanks again for making this great program you have saved me a ton of time.

**Comment by tomreece** [comment]
Please add a comment and +1 this or contact me in some way if you want this feature, otherwise it's going to stay "common" priority (aka low).

**Comment by Wizard37** [comment]
I prefer just using the site's blocking features as a way to mitigate this.

**Comment by tomreece** [comment]
I agree @Wizard37. Closing this issue.
