### ISSUE TITLE
Rarely sending multiples of a card to the same user even if I only have 1 copy

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#45]
Reported by Dominick:

> I came across a bug recently where the bot will add multiples of a card if a user ask for more than one even if I only have one on my haves list. This seems to happen very rarely but I have had it happen twice now the first time was on an older version but I noticed it just happened today on version .4.1

**Comment by tomreece** [comment]
I briefly investigated this and nothing stood out that would cause this behavior. Will require a deeper dive.

**Comment by tomreece** [comment]
New info from Dominick:

> I believe I discovered the problem behind this bug. It's on puca's end. After sending a card it doesn't always remove it from your list even if it's not on your list anymore if that makes sense? For example it sent a card out worth 300 points but keeps trying to send another copy to the same person because they want a second one as well. However the have lists that I only had one but still continues to show up on the send page. 

I too have seen a situation where I added a Polluted Delta to my Haves list, checked my Trades page to see that a lot of people wanted it, then just removed the Polluted Delta from my Haves list and my Trades page continued to show people wanting Polluted Delta's for like 3 to 5 minutes.

PucaTrade must be doing some caching on their end, which kind of sucks but I can understand why.

TODO: Send them an email reporting Trades page caching as a bug, because even if you're not using Pucauto it would be really easy to send out a card you actually don't even have.

**Comment by tomreece** [comment]
I sent the following email to admin@pucatrade.com

> Hello,
> 
> Sometimes my "Send Cards" page will show cards that I actually no longer have on my Haves list because I either already sent out the single copy I had or because I removed it from my Haves list.
> 
> This is probably an effort on your part to cache, reduce server load, and page load time, but seeing out of date data can be detrimental. It causes me sometime commit to send another card even though I don't have a second copy to send.

**Comment by tomreece** [comment]
Closing this issue since there is really nothing I can do about it on Pucauto's end.

**Comment by xeroiv** [comment]
Just wanted to report that this bug is still happening.  Dont know if there is anything we could do on this end to lessen the chance of this happening.  I've had to open quite a few cases as of late.

**Comment by tomreece** [comment]
I've reproduced it manually, posted about it on Reddit, and reported it to PucaTrade:

https://www.reddit.com/r/PucaTrade/comments/4570l8/duplicate_rows_on_the_send_cards_page_even_with/

**Comment by tomreece** [comment]
This doesn't seem to be happening anymore. I believe PucaTrade fixed the issue on their end.
