### ISSUE TITLE
Allow Facebook login

### ISSUE THREAD

**Issue by tomreece** [tomreece/pucauto#5]
Allow an extra flag to be passed in when running the script that will log the user in via Facebook instead of normal. The user will have to provide their Facebook username and password when using this new startup flag, then Pucauto would just click a different button and perhaps have to interact with a new popup window. That may be challenging.

**Comment by tomreece** [comment]
Does anyone actually want this? No one has asked for it.

**Comment by tomreece** [comment]
Add a comment or contact me in some way if you want this feature. Otherwise it's on the chopping black for removal because no one has asked for it.

**Comment by eengstrom** [comment]
-1 ;-)

**Comment by tomreece** [comment]
If someone actually wants this. They can open another issue. Until then. Bye bye!
