### ISSUE TITLE
Auto-match Set Failure

### ISSUE THREAD

**Issue by isutrumpet** [tomreece/pucauto#51]
I just started up v0.4.2 in the background, and noticed after about 15 minutes that the auto-match was off, and the bot had sent several cards (e.g., expeditions) that I unfortunately do not own.  Not sure if there was a code change that would cause this, but it might be worth adding some sort of secondary check to ensure auto-match is functioning properly.  I managed to cancel the trades, but things could have gotten very messy.

Win 7 (VM)
Firefox 42
pucauto 0.4.2

**Comment by tomreece** [comment]
I think I know what causes this and fortunately it's pretty rare. I'll make a code change soon!

Can you send me your debug.log file? Or debug.log.1, debug.log.2, etc if you have those yet?

**Comment by isutrumpet** [comment]
Hi Tom - here is the file for the instance that failed to auto-match.

Thanks!

On Thu, Dec 10, 2015 at 6:18 PM, Tom Reece notifications@github.com wrote:

> Can you send me your debug.log file? Or debug.log.1, debug.log.2, etc if
> you have those yet?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomreece/pucauto/issues/51#issuecomment-163793539.

## 

Grant

**Comment by tomreece** [comment]
@isutrumpet I don't see any attachment. Am I crazy?

**Comment by tomreece** [comment]
This happens rarely, but is critically bad when it does happen. I think I can simply resolve it with an explicit wait after clicking the Auto Match toggle.

If your VM isn't headless, at the very least watch Pucauto run for the first 30 seconds or so of startup so you can see Auto Matching turn on. Once it's on, it should be safe and will never be turned off in any way that I can imagine.
