### ISSUE TITLE
Headless version of Pucauto

### ISSUE THREAD

**Issue by spam8117** [tomreece/pucauto#54]
Hello Tom, I don't know where your readme about running Pucauto on a Linux/Headless browser machine went, so I am asking here :) could you re-upload it maybe? I'd love to try it out sometime on my server.
Here are the installed scripts and programs:
https://whatbox.ca/wiki#installed_programs_and_scripts

Thank you :)

**Comment by tomreece** [comment]
@spam8117 I moved it out of the README and into a Wiki page found here: https://github.com/tomreece/pucauto/wiki/Cloud-Server-Setup

This explains how I set up the server I run Pucauto on.

**Comment by tomreece** [comment]
I hope that link helps you. If you need specific help getting it running in your particular environment, let me know in this issue or via email and I'd be glad to help more specifically. :)

**Comment by spam8117** [comment]
Thank you Tom, I will try it out soon :)

**Comment by tomreece** [comment]
You're welcome!
