### ISSUE TITLE
Higher Bundle Value than Member Points

### ISSUE THREAD

**Issue by twilightwolf90** [tomreece/pucauto#70]
It was actually a little harder to track down a common bug I was having.  I kept having pucauto attempt to send more cards than the member had points in a bundle trade.  The missing lines of logic to add a check that the bundle trade is less than the member's available points would fit somewhere around 330 in pucauto.py.  I can't fork and pull today, because I have class all day.

For example, (only when building the initial list of trades, do not repeat when accepting each individual trade) pucauto will output the line: "Found W cards worth X points to Y member who has Z points..."  However, X > Z, and pucauto will still attempt to send the cards.

In my opinion, in this case, it should fail to send any cards, and ignore the package completely.  However, if this is intended behavior, maybe because you are trying to catch someone whose points keep fluctuating, this can be closed with no changes.

EDIT~ This is somewhat similar to issue #32, however, I do believe the logic suggested is different.  If not, please merge or close. My apologies.

**Comment by tomreece** [comment]
Pucauto doesn't worry about X > Z. Pucauto wants X > min_value and Z > min_value where min_value comes from the config file.

So yes, it sometimes finds larger bundles that it couldn't possibly accept all of, but it will accept the highest value cards first and hopefully create a bundle > min_value.

Does this make sense?
