### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by DaxCommando** [tomreece/pucauto#74]
I'm trying to install on Windows and am having an issue right out of the gate.  I've downloaded python and checked the box to add it to Path.

My problem is that when I open the command window and try to run the command 'python...' i receive the message stating it isnt recognized.
I admit that this is my first time trying to use python or command windows as I'm not very computer or prgramming savvy.
 Any help for this newbie would be appreciated.  Thank you

**Comment by tomreece** [comment]
Are you able to try to install Python again and take a screenshot of the box you're checking? I remember it being a bit hidden. If I remember correctly there is an "advanced" install mode and you can select extra stuff to install/configure, and it's one hiding in that list.

**Comment by DaxCommando** [comment]
Thank you for the help!

Here are 2 screenshots, the first showing how I'm installing python, and
the second showing the message I am receiving when I type the command into
the command window.

**Comment by tomreece** [comment]
It doesn't look like your screenshots made it over with the reply to the email. You can send them to me at tomreece@gmail.com or add them directly to the GitHub issue.

**Comment by tomreece** [comment]
Hey @DaxCommando, I haven't heard back from you. See my previous comment, it looks like the screenshots didn't come through when you replied via email. If you want some personal assistance getting Pucauto setup, email me at tomreece@gmail.com and I'd be glad to help you. Closing this issue.
