### ISSUE TITLE
Error: ImportError: No module named six

### ISSUE THREAD

**Issue by tpblaster** [tomreece/pucauto#79]
For some reason when I try to start Pucauto on my Mac it shows this:

Traceback (most recent call last):
  File "pucauto.py", line 7, in <module>
    import six
ImportError: No module named six

I am in the right folder and have put in my username and password and renamed the file. What could be the problem? I am a bit of a noob at this so a simple answer would be apreciated. 

Thanks

**Comment by tomreece** [comment]
Have you ran `sudo pip install -r requirements.txt`? Run this from a Terminal window while inside the Pucauto directory. This installs the proper dependency libraries that Pucauto needs to run.

**Comment by tpblaster** [comment]
For some reason I am still getting the same error:

Traceback (most recent call last):
  File "pucauto.py", line 7, in <module>
    import six
ImportError: No module named six

When I run 'sudo pip install -r requirements.txt' this is what comes next:

The directory '/Users/xxxxx/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/xxxxx/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.4.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): selenium==2.48.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 3))

xxxxx replaces personal info.

**Comment by tomreece** [comment]
Try `sudo -H pip install -r requirements.txt`

**Comment by tpblaster** [comment]
Now I am getting this error:

Traceback (most recent call last):
  File "pucauto.py", line 15, in <module>
    CONFIG = json.load(config)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by tomreece** [comment]
So we're getting closer. I suspect you used TextEdit to modify your config.json. TextEdit turns quotes `"` into Smart Quotes which is not valid JSON. Delete your config.json file and start with config.example.json again and do this:

![smart-quotes](https://cloud.githubusercontent.com/assets/2057871/13485611/556bd3b0-e0cf-11e5-97f5-399adbca5a33.png)

or use a text editor like Sublime Text 2.

This should get you up and running. I will look for ways to make this initial setup process easier, but once you get past this you're on your way to automated trading happiness!

**Comment by tpblaster** [comment]
Thanks for all the help I am now up and running!

**Comment by tomreece** [comment]
Awesome! Let me know if you have any more problems or feature requests.
